package com.mybatis.Mapper;

import com.mybatis.Entity.ProductXML;
import com.mybatis.Entity.ProductXMLExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ProductXMLMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	long countByExample(ProductXMLExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	int deleteByExample(ProductXMLExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	int insert(ProductXML row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	int insertSelective(ProductXML row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	List<ProductXML> selectByExample(ProductXMLExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	ProductXML selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	int updateByExampleSelective(@Param("row") ProductXML row, @Param("example") ProductXMLExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	int updateByExample(@Param("row") ProductXML row, @Param("example") ProductXMLExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	int updateByPrimaryKeySelective(ProductXML row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	int updateByPrimaryKey(ProductXML row);
}