package com.mybatis.Entity;

public class ProductXML {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.name
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.status
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	private Boolean status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.id
	 * @param id  the value for product.id
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.name
	 * @return  the value of product.name
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.name
	 * @param name  the value for product.name
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.status
	 * @return  the value of product.status
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.status
	 * @param status  the value for product.status
	 * @mbg.generated  Wed Jan 17 14:52:40 ICT 2024
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}
}